<?php

return [
    "categorias_nome" => [
        1 => 'Acessórios Fisioterapia',
        2 => 'Acessórios Fitness',
        3 => 'Adquirentes',
        4 => 'Agências de Marketing',
        5 => 'Anilhas e Peso Livre',
        6 => 'Apps Fitness',
        7 => 'Arquitetura',
        8 => 'Avaliação Física',
        9 => 'Bebedouros',
        10 => 'Benefícios para Colaboradores',
        11 => 'Brindes e Acessórios',
        12 => 'Área Kids',
        13 => 'Catracas',
        14 => 'Comunicação Visual',
        15 => 'Consultoria Jurídica',
        16 => 'Convênios - Planos de saúde',
        17 => 'Corretora de Seguros',
        18 => 'Entidades Bancarias',
        19 => 'Entidades e Sindicatos',
        20 => 'Equipamentos Ar livre',
        21 => 'Equipamento Articulado',
        22 => 'Equipamentos Box / Funcional',
        23 => 'Equipamentos Cardio',
        24 => 'Equipamentos Musculação',
        25 => 'Universor Bike',
        26 => 'Estética',
        27 => 'Empresas Eventos',
        28 => 'Franquias',
        29 => 'Gadget',
        30 => 'Grafica',
        31 => 'Livraria',
        32 => 'Lojas de Sport',
        33 => 'Mentoria e Consultoria Fitness',
        34 => 'Confecção Sportiva',
        35 => 'Monitoramento',
        36 => 'Moveis de Decoração',
        37 => 'Nutrição Sportiva',
        38 => 'Suplementação',
        39 => 'Órgãos e Federações',
        40 => 'Pass Diárias',
        41 => 'Manuntenção e Reforma',
        42 => 'Pilates',
        43 => 'Pisos Profissionais e Grama',
        44 => 'Produtos Naturais',
        45 => 'Metadologia e Programas de Treinamento',
        46 => 'Rádio e TV Online',
        47 => 'Climatizadores',
        48 => 'Running',
        49 => 'Sistemas de Gestão',
        50 => 'Universidades',
        51 => 'Tecnologia',
        52 => 'Moda Vestuário',
    ],
];
